version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
  
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"