version: '3.9'

services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/usr/app
    ports:
      - '3000:3000'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123'
    ports:
      - "5432:5432"